-
  name: 'EmberAdapter Example :: Appliaction Frontend'
  uriPattern: ''
  defaults:
    '@package': 'Flow2Lab.EmberAdapter.Example'
    '@controller': 'Frontend'


#
# REST list
#
-
  name: 'EmberAdapter Example :: REST API tasks'
  uriPattern: 'api/1/tasks'
  defaults:
    '@package': 'Flow2Lab.EmberAdapter.Example'
    '@controller': 'Rest\Task'
    '@action': 'list'
    '@format': 'json'
  httpMethods: ['GET']

#
# REST Create
#
-
  name: 'EmberAdapter Example :: REST API Resource Identifier POST'
  uriPattern: 'api/1/tasks'
  defaults:
    '@package': 'Flow2Lab.EmberAdapter.Example'
    '@controller': 'Rest\Task'
    '@action': 'create'
    '@format': 'json'
  httpMethods: ['POST']
#
# REST Update
#
-
  name: 'EmberAdapter Example :: REST API Task UPDATE'
  uriPattern: 'api/1/tasks/{model}'
  defaults:
    '@package': 'Flow2Lab.EmberAdapter.Example'
    '@controller': 'Rest\Task'
    '@action': 'update'
    '@format': 'json'
  httpMethods: ['PUT']

#
# REST Delete
#
-
  name: 'EmberAdapter Example :: REST API Task DELETE'
  uriPattern: 'api/1/tasks/{model}'
  defaults:
    '@package': 'Flow2Lab.EmberAdapter.Example'
    '@controller': 'Rest\Task'
    '@action': 'delete'
    '@format': 'json'
  httpMethods: ['DELETE']


-
  name: 'EmberAdapter Example :: Controller with Argument'
  uriPattern: 'products/{product}'
  defaults:
    '@package': 'Flow2Lab.EmberAdapter.Example'
    '@controller': 'Product'
  httpMethods: ['GET', 'PUT', 'DELETE']

-
  name: 'EmberAdapter Example :: Controller'
  uriPattern: 'products'
  defaults:
    '@package': 'Flow2Lab.EmberAdapter.Example'
    '@controller': 'Product'
  httpMethods: ['GET', 'POST']

-
  name: 'EmberAdapter Example :: CategoryController with Argument'
  uriPattern: 'categories/{category}'
  defaults:
    '@package': 'Flow2Lab.EmberAdapter.Example'
    '@controller': 'Category'
  httpMethods: ['GET', 'PUT', 'DELETE']

-
  name: 'EmberAdapter Example :: CategoryController'
  uriPattern: 'categories'
  defaults:
    '@package': 'Flow2Lab.EmberAdapter.Example'
    '@controller': 'Category'
  httpMethods: ['GET', 'POST']